FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS installer-env

COPY . /src/app
RUN cd /src/app && mkdir -p /home/site/wwwroot && \
    dotnet publish *.csproj --output /home/site/wwwroot -c Release

FROM mcr.microsoft.com/azure-functions/dotnet:3.0

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=false

COPY --from=installer-env ["/home/site/wwwroot", "/home/site/wwwroot"]
